### ISSUE TITLE
train help

### ISSUE THREAD

**Issue by YZGod666** [ZZZ429/CC-DETR#1]
Hello, is your code file missing?
I:\Code\CC-DETR-main>python train.py
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from train_net import Trainer
  File "I:\Code\CC-DETR-main\train_net.py", line 14, in <module>
    from Networks import ALTGVT
ImportError: cannot import name 'ALTGVT' from 'Networks' (unknown location)

**Comment by ZZZ429** [comment]
I'm sorry, it should be right：from Networks import ALTGVT1
